 
PRAGMA foreign_keys=OFF;

DROP TABLE IF EXISTS MONTADORA;
DROP TABLE IF EXISTS MODELO;
DROP TABLE IF EXISTS CATEGORIA;
DROP TABLE IF EXISTS COMBUSTIVEL;
DROP TABLE IF EXISTS VEICULO;
DROP TABLE IF EXISTS USUARIO;
DROP TABLE IF EXISTS CLIENTE;
DROP TABLE IF EXISTS LOCACAO;
DROP TABLE IF EXISTS DEVOLUCAO;
DROP TABLE IF EXISTS BAIXA;

PRAGMA foreign_keys=ON;

CREATE TABLE MONTADORA(
	ID_MONTADORA INTEGER CONSTRAINT PK_MONTADORA PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME_MONTADORA VARCHAR(512) UNIQUE
	);

CREATE TABLE MODELO(
	ID_MODELO INTEGER CONSTRAINT PK_MODELO PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME_MODELO VARCHAR(512) UNIQUE,
	ID_MONTADORA INTEGER NOT NULL,
	CONSTRAINT FK_MONTADORA FOREIGN KEY(ID_MONTADORA) REFERENCES MONTADORA(ID_MONTADORA)
	);

CREATE TABLE CATEGORIA(
	ID_CATEGORIA INTEGER CONSTRAINT PK_CATEGORIA PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME_CATEGORIA VARCHAR(512) UNIQUE
	);

CREATE TABLE COMBUSTIVEL(
	ID_COMBUSTIVEL INTEGER CONSTRAINT PK_COMBUSTIVEL PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME_COMBUSTIVEL VARCHAR(512) UNIQUE
	);
	
CREATE TABLE VEICULO(
	ID_VEICULO INTEGER CONSTRAINT PK_VEICULO PRIMARY KEY AUTOINCREMENT NOT NULL,
	DESCRICAO VARCHAR(512),
	PLACA VARCHAR(10) UNIQUE,
	COR VARCHAR(20),
	ANO VARCHAR(10),
	DATA_CADASTRO DATE NOT NULL,
	VALOR_LOCACAO DOUBLE NOT NULL,
	VALOR_MULTA_DIARIA DOUBLE NOT NULL,
	ANOTACOES TEXT,
	STATUS VARCHAR(100) NOT NULL,
	ID_MODELO INTEGER NOT NULL,
	ID_CATEGORIA INTEGER NOT NULL,
	ID_COMBUSTIVEL INTEGER NOT NULL,
	CONSTRAINT FK_MODELO FOREIGN KEY(ID_MODELO) REFERENCES MODELO(ID_MODELO),
	CONSTRAINT FK_CATEGORIA FOREIGN KEY(ID_CATEGORIA) REFERENCES CATEGORIA(ID_CATEGORIA),
	CONSTRAINT FK_COMBUSTIVEL FOREIGN KEY(ID_COMBUSTIVEL) REFERENCES COMBUSTIVEL(ID_CONBUSTIVEL)
	);
	
CREATE TABLE USUARIO(
	ID_USUARIO INTEGER CONSTRAINT PK_USUARIO PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME_USUARIO VARCHAR(512) NOT NULL,
	LOGIN VARCHAR(100) UNIQUE,
	SENHA VARCHAR(512) NOT NULL,
	ADMINISTRADOR BOOLEAN NOT NULL DEFAULT 0,
	ATIVO BOOLEAN NOT NULL DEFAULT 0
	);
	
CREATE TABLE CLIENTE(
	ID_CLIENTE INTEGER CONSTRAINT PK_CLIENTE PRIMARY KEY AUTOINCREMENT NOT NULL,
	NOME_CLIENTE VARCHAR(512) NOT NULL,
	TIPO_PESSOA VARCHAR(10) NOT NULL,
	CPF_CNPJ VARCHAR(20) UNIQUE,
	TELEFONE VARCHAR(10) NOT NULL,
	CELULAR VARCHAR(11) NOT NULL,
	EMAIL VARCHAR(100) NOT NULL,
	CEP VARCHAR(8) NOT NULL,
	ENDERECO VARCHAR(512) NOT NULL,
	NUMERO VARCHAR(10) NOT NULL,
	BAIRRO VARCHAR(100) NOT NULL,
	ESTADO VARCHAR(100) NOT NULL,
	UF VARCHAR(2) NOT NULL,
	DATA_CADASTRO DATE NOT NULL,
	ANOTACOES TEXT,
	ID_USUARIO INTEGER NOT NULL,
	CONSTRAINT FK_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
	);

CREATE TABLE LOCACAO(
	ID_LOCACAO INTEGER CONSTRAINT PK_LOCACAO PRIMARY KEY AUTOINCREMENT NOT NULL,
	DATA_LOCACAO DATE NOT NULL,
	DATA_DEVOLUCAO DATE NOT NULL,
	VALOR_TOTAL_LOCACAO DOUBLE NOT NULL,
	ANOTACOES TEXT,
	STATUS VARCHAR(100) NOT NULL,
	ID_VEICULO INTEGER NOT NULL,
	ID_CLIENTE INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	CONSTRAINT FK_VEICULO FOREIGN KEY(ID_VEICULO) REFERENCES VEICULO(ID_VEICULO),
	CONSTRAINT FK_CLIENTE FOREIGN KEY(ID_CLIENTE) REFERENCES CLIENTE(ID_CLIENTE),
	CONSTRAINT FK_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
	);
	
CREATE TABLE DEVOLUCAO(
	ID_DEVOLUCAO INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	DATA_DEVOLUCAO DATE NOT NULL,
	VALOR_MULTA_TOTAL DOUBLE NOT NULL,
	ANOTACOES TEXT,
	ID_LOCACAO INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	CONSTRAINT FK_LOCACAO FOREIGN KEY(ID_LOCACAO) REFERENCES LOCACAO(ID_LOCACAO),
	CONSTRAINT FK_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
	);
	
CREATE TABLE BAIXA(
	ID_BAIXA INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL,
	DATA_BAIXA DATE NOT NULL,
	MOTIVO TEXT NOT NULL,
	ANOTACOES TEXT,
	ID_VEICULO INTEGER NOT NULL,
	ID_USUARIO INTEGER NOT NULL,
	CONSTRAINT FK_VEICULO FOREIGN KEY(ID_VEICULO) REFERENCES VEICULO(ID_VEICULO),
	CONSTRAINT FK_USUARIO FOREIGN KEY(ID_USUARIO) REFERENCES USUARIO(ID_USUARIO)
	);
	
	
INSERT INTO USUARIO(NOME_USUARIO, LOGIN, SENHA, ADMINISTRADOR, ATIVO) VALUES('Admin','admin','c7ad44cbad762a5da0a452f9e854fdc1e0e7a52a38015f23f3eab1d80b931dd472634dfac71cd34ebc35d16ab7fb8a90c81f975113d6c7538dc69dd8de9077ec',1,1);
INSERT INTO USUARIO(NOME_USUARIO, LOGIN, SENHA, ADMINISTRADOR, ATIVO) VALUES('Alberto Nunes de Souza','alberto','00030cfebc1160a08ca2e897cea102ad3bc5f6d0cac2c9bb13a093fd76604a50235f923b94c997a7ef9aa3198eb911f9da463d03943ed628c0c4599381a35890',1,1);
INSERT INTO USUARIO(NOME_USUARIO, LOGIN, SENHA, ADMINISTRADOR, ATIVO) VALUES('Jose Torquato dos Santos','jose','107d125c183b9cebc75f71f6c225879d17fb6a8edcc551372bccc85b6301ad8b69d8623700f83b78010b96e8e08e819e41f79a949d442b5de468bcc376884df6',0,1);
INSERT INTO USUARIO(NOME_USUARIO, LOGIN, SENHA, ADMINISTRADOR, ATIVO) VALUES('Augusto Pereira','augusto','b011787519cd1e4afb02556bd11727a60b24e2dc6daff804ec9103d6ad1d96054c67f6f36481f4cdc2247b05ac538d8edc66f03c8b3c9bedf8861066607a5221',0,0);


